- hosts: all
  tasks:
    - name: insert line
      lineinfile:
        path: "{{ configlinesinfile.path }}"
        insertafter: "{{ configlinesinfile.baseline }}"
        line: "{{ configlinesinfile.current }}"
      when: configlinesinfile.previous is undefined
    
    - name: replace line
      lineinfile:
        path: "{{ configlinesinfile.path }}"
        regexp: "{{ configlinesinfile.previous }}"
        line: "{{ configlinesinfile.current }}"
      when: configlinesinfile.previous is defined
