- hosts: all
  tasks:
    - name: config hosts file
      lineinfile:
        path: /etc/hosts
        insertafter: '^::1'
        line: |
          192.168.1.111 tester1
          192.168.1.112 tester2
